name: Bug report
about: Create a report to help us improve
labels: bug
assignees: ''

title: "[Bug] <short summary>"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened and what did you expect?
      placeholder: Clear and concise description
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Steps to reproduce in-game
      placeholder: 1) ... 2) ... 3) ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Game/Mod version
      placeholder: e.g., Bannerlord e1.x.x, Enlisted v0.x
  - type: textarea
    id: logs
    attributes:
      label: Logs/screenshots
      description: Drag-and-drop logs or screenshots
