using System.Collections.Generic;
using System.Linq;
using TaleWorlds.CampaignSystem;
using TaleWorlds.SaveSystem;

namespace Enlisted.Features.Schedule.Models
{
    /// <summary>
    /// Represents a complete daily schedule with 6 time blocks (one per TimeBlock enum).
    /// Generated by the AI scheduling system based on lord objectives and lance needs.
    /// </summary>
    public class DailySchedule
    {
        /// <summary>The day this schedule is for (campaign time)</summary>
        [SaveableProperty(1)]
        public CampaignTime ScheduleDate { get; set; }
        
        /// <summary>Day number in the current 12-day cycle (1-12)</summary>
        [SaveableProperty(2)]
        public int CycleDay { get; set; }
        
        /// <summary>List of 6 scheduled blocks (one per time period)</summary>
        [SaveableProperty(3)]
        public List<ScheduledBlock> Blocks { get; set; }
        
        /// <summary>Lord's current objective that influenced this schedule</summary>
        [SaveableProperty(4)]
        public string LordObjective { get; set; }
        
        /// <summary>Lord's orders text (displayed to player for context)</summary>
        [SaveableProperty(5)]
        public string LordOrders { get; set; }
        
        /// <summary>Whether this schedule has been shown to the player</summary>
        [SaveableProperty(6)]
        public bool HasBeenViewed { get; set; }

        /// <summary>AI decision log explaining why each activity was assigned (Phase 3)</summary>
        [SaveableProperty(7)]
        public string DecisionLog { get; set; }

        public DailySchedule()
        {
            Blocks = new List<ScheduledBlock>(6);
            LordObjective = string.Empty;
            LordOrders = string.Empty;
            HasBeenViewed = false;
            DecisionLog = string.Empty;
        }

        /// <summary>
        /// Create a daily schedule for a specific date.
        /// </summary>
        public DailySchedule(CampaignTime scheduleDate, int cycleDay)
        {
            ScheduleDate = scheduleDate;
            CycleDay = cycleDay;
            Blocks = new List<ScheduledBlock>(6);
            LordObjective = string.Empty;
            LordOrders = string.Empty;
            HasBeenViewed = false;
            DecisionLog = string.Empty;
        }

        /// <summary>
        /// Get the block for a specific time period.
        /// </summary>
        public ScheduledBlock GetBlock(TimeBlock timeBlock)
        {
            return Blocks.FirstOrDefault(b => b.TimeBlock == timeBlock);
        }

        /// <summary>
        /// Get the currently active block (if any).
        /// </summary>
        public ScheduledBlock GetActiveBlock()
        {
            return Blocks.FirstOrDefault(b => b.IsActive);
        }

        /// <summary>
        /// Check if all blocks are completed.
        /// </summary>
        public bool IsFullyCompleted()
        {
            return Blocks.All(b => b.IsCompleted);
        }

        /// <summary>
        /// Get completion percentage (0-100).
        /// </summary>
        public int GetCompletionPercentage()
        {
            if (Blocks.Count == 0) return 0;
            int completed = Blocks.Count(b => b.IsCompleted);
            return (completed * 100) / Blocks.Count;
        }

        /// <summary>
        /// Add a block to the schedule.
        /// </summary>
        public void AddBlock(ScheduledBlock block)
        {
            Blocks.Add(block);
        }
    }
}

